name: cagenix-os
description: Cagenix OS

base-image: ghcr.io/ublue-os/base-asus-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: sddm-packages.yml
  - from-file: common-packages.yml
  - from-file: hyprland-packages.yml
  - from-file: hyprland-files.yml
  - from-file: common-files.yml
  - from-file: common-scripts.yml
  - from-file: hyprland-scripts.yml  
  - from-file: sddm-scripts.yml
  - type: signing
  - from-file: sddm-systemd.yml

